name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features:
          - --all-features
          - --no-default-features

    steps:
      - uses: actions/checkout@v2
      - name: Build (${{ matrix.features }})
        run: cargo build --verbose ${{ matrix.features }}
      - name: Run tests (${{ matrix.features }})
        run: cargo test --verbose ${{ matrix.features }}
